//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLF.DAS.DB.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Const {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Const() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VLF.DAS.DB.Resources.Const", typeof(Const).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm.
        /// </summary>
        internal static string Alarm {
            get {
                return ResourceManager.GetString("Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string alright {
            get {
                return ResourceManager.GetString("alright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        internal static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration: .
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine Idle.
        /// </summary>
        internal static string EngineIdle {
            get {
                return ResourceManager.GetString("EngineIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string extinct {
            get {
                return ResourceManager.GetString("extinct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extreme Acceleration.
        /// </summary>
        internal static string ExtremeAcceleration {
            get {
                return ResourceManager.GetString("ExtremeAcceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extreme Braking.
        /// </summary>
        internal static string ExtremeBraking {
            get {
                return ResourceManager.GetString("ExtremeBraking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in broken.
        /// </summary>
        internal static string fenceDirection_inbroken {
            get {
                return ResourceManager.GetString("fenceDirection_inbroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to out broken.
        /// </summary>
        internal static string fenceDirection_outbroken {
            get {
                return ResourceManager.GetString("fenceDirection_outbroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown direction.
        /// </summary>
        internal static string fenceDirection_unknown {
            get {
                return ResourceManager.GetString("fenceDirection_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geo Zone.
        /// </summary>
        internal static string GeoZone {
            get {
                return ResourceManager.GetString("GeoZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harsh Acceleration.
        /// </summary>
        internal static string HarshAcceleration {
            get {
                return ResourceManager.GetString("HarshAcceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harsh Braking.
        /// </summary>
        internal static string HarshBraking {
            get {
                return ResourceManager.GetString("HarshBraking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idling.
        /// </summary>
        internal static string Idling {
            get {
                return ResourceManager.GetString("Idling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string OFF {
            get {
                return ResourceManager.GetString("OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string ON {
            get {
                return ResourceManager.GetString("ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PTO.
        /// </summary>
        internal static string PTO {
            get {
                return ResourceManager.GetString("PTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seat Belt Violation.
        /// </summary>
        internal static string SeatBeltViolation {
            get {
                return ResourceManager.GetString("SeatBeltViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor.
        /// </summary>
        internal static string Sensor {
            get {
                return ResourceManager.GetString("Sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speeding.
        /// </summary>
        internal static string Speeding {
            get {
                return ResourceManager.GetString("Speeding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        internal static string Stopped {
            get {
                return ResourceManager.GetString("Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored Position.
        /// </summary>
        internal static string StoredPosition {
            get {
                return ResourceManager.GetString("StoredPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tractor Power.
        /// </summary>
        internal static string TP {
            get {
                return ResourceManager.GetString("TP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip End.
        /// </summary>
        internal static string TripEnd {
            get {
                return ResourceManager.GetString("TripEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Start.
        /// </summary>
        internal static string TripStart {
            get {
                return ResourceManager.GetString("TripStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Message.
        /// </summary>
        internal static string TxtMessage {
            get {
                return ResourceManager.GetString("TxtMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answers.
        /// </summary>
        internal static string TxtMsgAnswers {
            get {
                return ResourceManager.GetString("TxtMsgAnswers", resourceCulture);
            }
        }
    }
}
