//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace SentinelMobile.SecurityManager {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SecurityManagerSoap", Namespace="http://www.sentinelfm.com")]
    public partial class SecurityManager : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginUserMD5OperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginMD5OperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginMD5ExtendedOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginMD5ByDBNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginSHAOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogoutOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReloginOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReloginMD5OperationCompleted;
        
        private System.Threading.SendOrPostCallback ReloginMD5ByDBNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateandReloginMD5ByDBNameOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SecurityManager() {
            this.Url = global::SentinelMobile.Properties.Settings.Default.SentinelMobile_SecurityManager_SecurityManager;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event LoginUserMD5CompletedEventHandler LoginUserMD5Completed;
        
        /// <remarks/>
        public event LoginMD5CompletedEventHandler LoginMD5Completed;
        
        /// <remarks/>
        public event LoginMD5ExtendedCompletedEventHandler LoginMD5ExtendedCompleted;
        
        /// <remarks/>
        public event LoginMD5ByDBNameCompletedEventHandler LoginMD5ByDBNameCompleted;
        
        /// <remarks/>
        public event LoginSHACompletedEventHandler LoginSHACompleted;
        
        /// <remarks/>
        public event LogoutCompletedEventHandler LogoutCompleted;
        
        /// <remarks/>
        public event ReloginCompletedEventHandler ReloginCompleted;
        
        /// <remarks/>
        public event ReloginMD5CompletedEventHandler ReloginMD5Completed;
        
        /// <remarks/>
        public event ReloginMD5ByDBNameCompletedEventHandler ReloginMD5ByDBNameCompleted;
        
        /// <remarks/>
        public event ValidateandReloginMD5ByDBNameCompletedEventHandler ValidateandReloginMD5ByDBNameCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sentinelfm.com/Login", RequestNamespace="http://www.sentinelfm.com", ResponseNamespace="http://www.sentinelfm.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Login(string userName, string password, string userIp, ref int userId, ref string SID) {
            object[] results = this.Invoke("Login", new object[] {
                        userName,
                        password,
                        userIp,
                        userId,
                        SID});
            userId = ((int)(results[1]));
            SID = ((string)(results[2]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string userName, string password, string userIp, int userId, string SID) {
            this.LoginAsync(userName, password, userIp, userId, SID, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string userName, string password, string userIp, int userId, string SID, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        userName,
                        password,
                        userIp,
                        userId,
                        SID}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sentinelfm.com/LoginUserMD5", RequestNamespace="http://www.sentinelfm.com", ResponseNamespace="http://www.sentinelfm.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int LoginUserMD5(string userName, string password, ref string passKey) {
            object[] results = this.Invoke("LoginUserMD5", new object[] {
                        userName,
                        password,
                        passKey});
            passKey = ((string)(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void LoginUserMD5Async(string userName, string password, string passKey) {
            this.LoginUserMD5Async(userName, password, passKey, null);
        }
        
        /// <remarks/>
        public void LoginUserMD5Async(string userName, string password, string passKey, object userState) {
            if ((this.LoginUserMD5OperationCompleted == null)) {
                this.LoginUserMD5OperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginUserMD5OperationCompleted);
            }
            this.InvokeAsync("LoginUserMD5", new object[] {
                        userName,
                        password,
                        passKey}, this.LoginUserMD5OperationCompleted, userState);
        }
        
        private void OnLoginUserMD5OperationCompleted(object arg) {
            if ((this.LoginUserMD5Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginUserMD5Completed(this, new LoginUserMD5CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sentinelfm.com/LoginMD5", RequestNamespace="http://www.sentinelfm.com", ResponseNamespace="http://www.sentinelfm.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int LoginMD5(string key, string userName, string password, string userIp, ref int userId, ref string SID) {
            object[] results = this.Invoke("LoginMD5", new object[] {
                        key,
                        userName,
                        password,
                        userIp,
                        userId,
                        SID});
            userId = ((int)(results[1]));
            SID = ((string)(results[2]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void LoginMD5Async(string key, string userName, string password, string userIp, int userId, string SID) {
            this.LoginMD5Async(key, userName, password, userIp, userId, SID, null);
        }
        
        /// <remarks/>
        public void LoginMD5Async(string key, string userName, string password, string userIp, int userId, string SID, object userState) {
            if ((this.LoginMD5OperationCompleted == null)) {
                this.LoginMD5OperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginMD5OperationCompleted);
            }
            this.InvokeAsync("LoginMD5", new object[] {
                        key,
                        userName,
                        password,
                        userIp,
                        userId,
                        SID}, this.LoginMD5OperationCompleted, userState);
        }
        
        private void OnLoginMD5OperationCompleted(object arg) {
            if ((this.LoginMD5Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginMD5Completed(this, new LoginMD5CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sentinelfm.com/LoginMD5Extended", RequestNamespace="http://www.sentinelfm.com", ResponseNamespace="http://www.sentinelfm.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int LoginMD5Extended(string key, string userName, string password, string userIp, ref int userId, ref string SID, ref int SuperOrganizationId) {
            object[] results = this.Invoke("LoginMD5Extended", new object[] {
                        key,
                        userName,
                        password,
                        userIp,
                        userId,
                        SID,
                        SuperOrganizationId});
            userId = ((int)(results[1]));
            SID = ((string)(results[2]));
            SuperOrganizationId = ((int)(results[3]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void LoginMD5ExtendedAsync(string key, string userName, string password, string userIp, int userId, string SID, int SuperOrganizationId) {
            this.LoginMD5ExtendedAsync(key, userName, password, userIp, userId, SID, SuperOrganizationId, null);
        }
        
        /// <remarks/>
        public void LoginMD5ExtendedAsync(string key, string userName, string password, string userIp, int userId, string SID, int SuperOrganizationId, object userState) {
            if ((this.LoginMD5ExtendedOperationCompleted == null)) {
                this.LoginMD5ExtendedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginMD5ExtendedOperationCompleted);
            }
            this.InvokeAsync("LoginMD5Extended", new object[] {
                        key,
                        userName,
                        password,
                        userIp,
                        userId,
                        SID,
                        SuperOrganizationId}, this.LoginMD5ExtendedOperationCompleted, userState);
        }
        
        private void OnLoginMD5ExtendedOperationCompleted(object arg) {
            if ((this.LoginMD5ExtendedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginMD5ExtendedCompleted(this, new LoginMD5ExtendedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sentinelfm.com/LoginMD5ByDBName", RequestNamespace="http://www.sentinelfm.com", ResponseNamespace="http://www.sentinelfm.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int LoginMD5ByDBName(string key, string userName, string password, string userIp, string dbName, ref int userId, ref string SID, ref int SuperOrganizationId) {
            object[] results = this.Invoke("LoginMD5ByDBName", new object[] {
                        key,
                        userName,
                        password,
                        userIp,
                        dbName,
                        userId,
                        SID,
                        SuperOrganizationId});
            userId = ((int)(results[1]));
            SID = ((string)(results[2]));
            SuperOrganizationId = ((int)(results[3]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void LoginMD5ByDBNameAsync(string key, string userName, string password, string userIp, string dbName, int userId, string SID, int SuperOrganizationId) {
            this.LoginMD5ByDBNameAsync(key, userName, password, userIp, dbName, userId, SID, SuperOrganizationId, null);
        }
        
        /// <remarks/>
        public void LoginMD5ByDBNameAsync(string key, string userName, string password, string userIp, string dbName, int userId, string SID, int SuperOrganizationId, object userState) {
            if ((this.LoginMD5ByDBNameOperationCompleted == null)) {
                this.LoginMD5ByDBNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginMD5ByDBNameOperationCompleted);
            }
            this.InvokeAsync("LoginMD5ByDBName", new object[] {
                        key,
                        userName,
                        password,
                        userIp,
                        dbName,
                        userId,
                        SID,
                        SuperOrganizationId}, this.LoginMD5ByDBNameOperationCompleted, userState);
        }
        
        private void OnLoginMD5ByDBNameOperationCompleted(object arg) {
            if ((this.LoginMD5ByDBNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginMD5ByDBNameCompleted(this, new LoginMD5ByDBNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sentinelfm.com/LoginSHA", RequestNamespace="http://www.sentinelfm.com", ResponseNamespace="http://www.sentinelfm.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int LoginSHA(string userName, string password, string userIp, ref int userId, ref string SID) {
            object[] results = this.Invoke("LoginSHA", new object[] {
                        userName,
                        password,
                        userIp,
                        userId,
                        SID});
            userId = ((int)(results[1]));
            SID = ((string)(results[2]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void LoginSHAAsync(string userName, string password, string userIp, int userId, string SID) {
            this.LoginSHAAsync(userName, password, userIp, userId, SID, null);
        }
        
        /// <remarks/>
        public void LoginSHAAsync(string userName, string password, string userIp, int userId, string SID, object userState) {
            if ((this.LoginSHAOperationCompleted == null)) {
                this.LoginSHAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginSHAOperationCompleted);
            }
            this.InvokeAsync("LoginSHA", new object[] {
                        userName,
                        password,
                        userIp,
                        userId,
                        SID}, this.LoginSHAOperationCompleted, userState);
        }
        
        private void OnLoginSHAOperationCompleted(object arg) {
            if ((this.LoginSHACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginSHACompleted(this, new LoginSHACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sentinelfm.com/Logout", RequestNamespace="http://www.sentinelfm.com", ResponseNamespace="http://www.sentinelfm.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Logout(int userId, string SID) {
            object[] results = this.Invoke("Logout", new object[] {
                        userId,
                        SID});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void LogoutAsync(int userId, string SID) {
            this.LogoutAsync(userId, SID, null);
        }
        
        /// <remarks/>
        public void LogoutAsync(int userId, string SID, object userState) {
            if ((this.LogoutOperationCompleted == null)) {
                this.LogoutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogoutOperationCompleted);
            }
            this.InvokeAsync("Logout", new object[] {
                        userId,
                        SID}, this.LogoutOperationCompleted, userState);
        }
        
        private void OnLogoutOperationCompleted(object arg) {
            if ((this.LogoutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogoutCompleted(this, new LogoutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sentinelfm.com/Relogin", RequestNamespace="http://www.sentinelfm.com", ResponseNamespace="http://www.sentinelfm.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Relogin(string userName, string password, string userIp, ref string SID) {
            object[] results = this.Invoke("Relogin", new object[] {
                        userName,
                        password,
                        userIp,
                        SID});
            SID = ((string)(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ReloginAsync(string userName, string password, string userIp, string SID) {
            this.ReloginAsync(userName, password, userIp, SID, null);
        }
        
        /// <remarks/>
        public void ReloginAsync(string userName, string password, string userIp, string SID, object userState) {
            if ((this.ReloginOperationCompleted == null)) {
                this.ReloginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReloginOperationCompleted);
            }
            this.InvokeAsync("Relogin", new object[] {
                        userName,
                        password,
                        userIp,
                        SID}, this.ReloginOperationCompleted, userState);
        }
        
        private void OnReloginOperationCompleted(object arg) {
            if ((this.ReloginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReloginCompleted(this, new ReloginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sentinelfm.com/ReloginMD5", RequestNamespace="http://www.sentinelfm.com", ResponseNamespace="http://www.sentinelfm.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ReloginMD5(string key, string userName, string password, string userIp, ref string SID) {
            object[] results = this.Invoke("ReloginMD5", new object[] {
                        key,
                        userName,
                        password,
                        userIp,
                        SID});
            SID = ((string)(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ReloginMD5Async(string key, string userName, string password, string userIp, string SID) {
            this.ReloginMD5Async(key, userName, password, userIp, SID, null);
        }
        
        /// <remarks/>
        public void ReloginMD5Async(string key, string userName, string password, string userIp, string SID, object userState) {
            if ((this.ReloginMD5OperationCompleted == null)) {
                this.ReloginMD5OperationCompleted = new System.Threading.SendOrPostCallback(this.OnReloginMD5OperationCompleted);
            }
            this.InvokeAsync("ReloginMD5", new object[] {
                        key,
                        userName,
                        password,
                        userIp,
                        SID}, this.ReloginMD5OperationCompleted, userState);
        }
        
        private void OnReloginMD5OperationCompleted(object arg) {
            if ((this.ReloginMD5Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReloginMD5Completed(this, new ReloginMD5CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sentinelfm.com/ReloginMD5ByDBName", RequestNamespace="http://www.sentinelfm.com", ResponseNamespace="http://www.sentinelfm.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ReloginMD5ByDBName(int userId, string key, string userName, string password, string userIp, ref string SID) {
            object[] results = this.Invoke("ReloginMD5ByDBName", new object[] {
                        userId,
                        key,
                        userName,
                        password,
                        userIp,
                        SID});
            SID = ((string)(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ReloginMD5ByDBNameAsync(int userId, string key, string userName, string password, string userIp, string SID) {
            this.ReloginMD5ByDBNameAsync(userId, key, userName, password, userIp, SID, null);
        }
        
        /// <remarks/>
        public void ReloginMD5ByDBNameAsync(int userId, string key, string userName, string password, string userIp, string SID, object userState) {
            if ((this.ReloginMD5ByDBNameOperationCompleted == null)) {
                this.ReloginMD5ByDBNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReloginMD5ByDBNameOperationCompleted);
            }
            this.InvokeAsync("ReloginMD5ByDBName", new object[] {
                        userId,
                        key,
                        userName,
                        password,
                        userIp,
                        SID}, this.ReloginMD5ByDBNameOperationCompleted, userState);
        }
        
        private void OnReloginMD5ByDBNameOperationCompleted(object arg) {
            if ((this.ReloginMD5ByDBNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReloginMD5ByDBNameCompleted(this, new ReloginMD5ByDBNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sentinelfm.com/ValidateandReloginMD5ByDBName", RequestNamespace="http://www.sentinelfm.com", ResponseNamespace="http://www.sentinelfm.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ValidateandReloginMD5ByDBName(int userId, string key, string userName, string password, string userIp, ref string SID) {
            object[] results = this.Invoke("ValidateandReloginMD5ByDBName", new object[] {
                        userId,
                        key,
                        userName,
                        password,
                        userIp,
                        SID});
            SID = ((string)(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateandReloginMD5ByDBNameAsync(int userId, string key, string userName, string password, string userIp, string SID) {
            this.ValidateandReloginMD5ByDBNameAsync(userId, key, userName, password, userIp, SID, null);
        }
        
        /// <remarks/>
        public void ValidateandReloginMD5ByDBNameAsync(int userId, string key, string userName, string password, string userIp, string SID, object userState) {
            if ((this.ValidateandReloginMD5ByDBNameOperationCompleted == null)) {
                this.ValidateandReloginMD5ByDBNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateandReloginMD5ByDBNameOperationCompleted);
            }
            this.InvokeAsync("ValidateandReloginMD5ByDBName", new object[] {
                        userId,
                        key,
                        userName,
                        password,
                        userIp,
                        SID}, this.ValidateandReloginMD5ByDBNameOperationCompleted, userState);
        }
        
        private void OnValidateandReloginMD5ByDBNameOperationCompleted(object arg) {
            if ((this.ValidateandReloginMD5ByDBNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateandReloginMD5ByDBNameCompleted(this, new ValidateandReloginMD5ByDBNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int userId {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string SID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void LoginUserMD5CompletedEventHandler(object sender, LoginUserMD5CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginUserMD5CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginUserMD5CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string passKey {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void LoginMD5CompletedEventHandler(object sender, LoginMD5CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginMD5CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginMD5CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int userId {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string SID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void LoginMD5ExtendedCompletedEventHandler(object sender, LoginMD5ExtendedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginMD5ExtendedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginMD5ExtendedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int userId {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string SID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public int SuperOrganizationId {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[3]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void LoginMD5ByDBNameCompletedEventHandler(object sender, LoginMD5ByDBNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginMD5ByDBNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginMD5ByDBNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int userId {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string SID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public int SuperOrganizationId {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[3]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void LoginSHACompletedEventHandler(object sender, LoginSHACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginSHACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginSHACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int userId {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string SID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void LogoutCompletedEventHandler(object sender, LogoutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LogoutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LogoutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ReloginCompletedEventHandler(object sender, ReloginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReloginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReloginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string SID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ReloginMD5CompletedEventHandler(object sender, ReloginMD5CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReloginMD5CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReloginMD5CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string SID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ReloginMD5ByDBNameCompletedEventHandler(object sender, ReloginMD5ByDBNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReloginMD5ByDBNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReloginMD5ByDBNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string SID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ValidateandReloginMD5ByDBNameCompletedEventHandler(object sender, ValidateandReloginMD5ByDBNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateandReloginMD5ByDBNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateandReloginMD5ByDBNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string SID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591