//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SentinelMobile.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://asi1.sentinelfm.com/ASI/Interfaces/DBFleet.asmx")]
        public string SentinelMobile_DBFleet_DBFleet {
            get {
                return ((string)(this["SentinelMobile_DBFleet_DBFleet"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.9.10/ASINew/Interfaces/DBUser.asmx")]
        public string SentinelMobile_ServerDBUser_DBUser {
            get {
                return ((string)(this["SentinelMobile_ServerDBUser_DBUser"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.9.10/ASINew/Interfaces/SecurityManager.asmx")]
        public string SentinelMobile_SecurityManager_SecurityManager {
            get {
                return ((string)(this["SentinelMobile_SecurityManager_SecurityManager"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.9.10/ASINew/Interfaces/DBOrganization.asmx")]
        public string SentinelMobile_ServerDBOrganization_DBOrganization {
            get {
                return ((string)(this["SentinelMobile_ServerDBOrganization_DBOrganization"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.9.9/Resolver.asmx")]
        public string SentinelMobile_Resolver_Resolver {
            get {
                return ((string)(this["SentinelMobile_Resolver_Resolver"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.9.10/ASINew/Interfaces/DBHistory.asmx")]
        public string SentinelMobile_ServerDBHistory_DBHistory {
            get {
                return ((string)(this["SentinelMobile_ServerDBHistory_DBHistory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.9.10/ASINew/Interfaces/Location.asmx")]
        public string SentinelMobile_LocationMgr_Location {
            get {
                return ((string)(this["SentinelMobile_LocationMgr_Location"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.9.29/ASINew/Interfaces/DBVehicle.asmx")]
        public string SentinelMobile_ServerDBVehicle_DBVehicle {
            get {
                return ((string)(this["SentinelMobile_ServerDBVehicle_DBVehicle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.9.10/ASINew/Interfaces/DBSystem.asmx")]
        public string SentinelMobile_ServerDBSystem_DBSystem {
            get {
                return ((string)(this["SentinelMobile_ServerDBSystem_DBSystem"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.9.45/HOSWS/HOSFileRetriver.asmx")]
        public string SentinelMobile_Hos_Ws_HOSFileReteriver {
            get {
                return ((string)(this["SentinelMobile_Hos_Ws_HOSFileReteriver"]));
            }
        }
    }
}
