//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalizationLayer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Const {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Const() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocalizationLayer.Const", typeof(Const).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DTC codes.
        /// </summary>
        internal static string Alarm_DTCcodes {
            get {
                return ResourceManager.GetString("Alarm_DTCcodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        internal static string Alarm_In {
            get {
                return ResourceManager.GetString("Alarm_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leash Broken.
        /// </summary>
        internal static string Alarm_LeashBroken {
            get {
                return ResourceManager.GetString("Alarm_LeashBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion Sensor.
        /// </summary>
        internal static string Alarm_MotionSensor {
            get {
                return ResourceManager.GetString("Alarm_MotionSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out.
        /// </summary>
        internal static string Alarm_Out {
            get {
                return ResourceManager.GetString("Alarm_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Connected / Tamper.
        /// </summary>
        internal static string Alarm_PowerConnected {
            get {
                return ResourceManager.GetString("Alarm_PowerConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rear Hopper Door.
        /// </summary>
        internal static string Alarm_RearHopperDoor {
            get {
                return ResourceManager.GetString("Alarm_RearHopperDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamper Alert.
        /// </summary>
        internal static string Alarm_TamperAlert {
            get {
                return ResourceManager.GetString("Alarm_TamperAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical.
        /// </summary>
        internal static string AlarmSeverity_Critical {
            get {
                return ResourceManager.GetString("AlarmSeverity_Critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoAlarm.
        /// </summary>
        internal static string AlarmSeverity_NoAlarm {
            get {
                return ResourceManager.GetString("AlarmSeverity_NoAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify.
        /// </summary>
        internal static string AlarmSeverity_Notify {
            get {
                return ResourceManager.GetString("AlarmSeverity_Notify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string AlarmSeverity_Warning {
            get {
                return ResourceManager.GetString("AlarmSeverity_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        internal static string AlarmState_Accepted {
            get {
                return ResourceManager.GetString("AlarmState_Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string AlarmState_Closed {
            get {
                return ResourceManager.GetString("AlarmState_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string AlarmState_New {
            get {
                return ResourceManager.GetString("AlarmState_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string AlarmState_Unknown {
            get {
                return ResourceManager.GetString("AlarmState_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address resolution in progress.
        /// </summary>
        internal static string InvalidAddress_addressNA {
            get {
                return ResourceManager.GetString("InvalidAddress_addressNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No GPS Data.
        /// </summary>
        internal static string InvalidAddress_noGPSData {
            get {
                return ResourceManager.GetString("InvalidAddress_noGPSData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Valid GPS Data.
        /// </summary>
        internal static string InvalidAddress_noValidAddress {
            get {
                return ResourceManager.GetString("InvalidAddress_noValidAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm.
        /// </summary>
        internal static string MessageType_Alarm {
            get {
                return ResourceManager.GetString("MessageType_Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BadSensor.
        /// </summary>
        internal static string MessageType_BadSensor {
            get {
                return ResourceManager.GetString("MessageType_BadSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinate.
        /// </summary>
        internal static string MessageType_Coordinate {
            get {
                return ResourceManager.GetString("MessageType_Coordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door.
        /// </summary>
        internal static string MessageType_Door {
            get {
                return ResourceManager.GetString("MessageType_Door", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string MessageType_Duration {
            get {
                return ResourceManager.GetString("MessageType_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExtremeAcceleration.
        /// </summary>
        internal static string MessageType_ExtremeAcceleration {
            get {
                return ResourceManager.GetString("MessageType_ExtremeAcceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExtremeBraking.
        /// </summary>
        internal static string MessageType_ExtremeBraking {
            get {
                return ResourceManager.GetString("MessageType_ExtremeBraking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoFence.
        /// </summary>
        internal static string MessageType_GeoFence {
            get {
                return ResourceManager.GetString("MessageType_GeoFence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPSAntennaOK.
        /// </summary>
        internal static string MessageType_GPSAntennaOK {
            get {
                return ResourceManager.GetString("MessageType_GPSAntennaOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPSAntennaOpen.
        /// </summary>
        internal static string MessageType_GPSAntennaOpen {
            get {
                return ResourceManager.GetString("MessageType_GPSAntennaOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPSAntennaShort.
        /// </summary>
        internal static string MessageType_GPSAntennaShort {
            get {
                return ResourceManager.GetString("MessageType_GPSAntennaShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HarshAcceleration.
        /// </summary>
        internal static string MessageType_HarshAcceleration {
            get {
                return ResourceManager.GetString("MessageType_HarshAcceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HarshBraking.
        /// </summary>
        internal static string MessageType_HarshBraking {
            get {
                return ResourceManager.GetString("MessageType_HarshBraking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idling.
        /// </summary>
        internal static string MessageType_Idling {
            get {
                return ResourceManager.GetString("MessageType_Idling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignition.
        /// </summary>
        internal static string MessageType_Ignition {
            get {
                return ResourceManager.GetString("MessageType_Ignition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyFobArm.
        /// </summary>
        internal static string MessageType_KeyFobArm {
            get {
                return ResourceManager.GetString("MessageType_KeyFobArm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyFobDisarm.
        /// </summary>
        internal static string MessageType_KeyFobDisarm {
            get {
                return ResourceManager.GetString("MessageType_KeyFobDisarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyFobPanic.
        /// </summary>
        internal static string MessageType_KeyFobPanic {
            get {
                return ResourceManager.GetString("MessageType_KeyFobPanic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string MessageType_Low {
            get {
                return ResourceManager.GetString("MessageType_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Battery.
        /// </summary>
        internal static string MessageType_Main_Battery {
            get {
                return ResourceManager.GetString("MessageType_Main_Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string MessageType_Off {
            get {
                return ResourceManager.GetString("MessageType_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string MessageType_On {
            get {
                return ResourceManager.GetString("MessageType_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string MessageType_Open {
            get {
                return ResourceManager.GetString("MessageType_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passenger In Seat.
        /// </summary>
        internal static string MessageType_Passenger_In_Seat {
            get {
                return ResourceManager.GetString("MessageType_Passenger_In_Seat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SeatBelt.
        /// </summary>
        internal static string MessageType_SeatBelt {
            get {
                return ResourceManager.GetString("MessageType_SeatBelt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor.
        /// </summary>
        internal static string MessageType_Sensor {
            get {
                return ResourceManager.GetString("MessageType_Sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string MessageType_Speed {
            get {
                return ResourceManager.GetString("MessageType_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speeding.
        /// </summary>
        internal static string MessageType_Speeding {
            get {
                return ResourceManager.GetString("MessageType_Speeding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string MessageType_Status {
            get {
                return ResourceManager.GetString("MessageType_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StoredPosition.
        /// </summary>
        internal static string MessageType_StoredPosition {
            get {
                return ResourceManager.GetString("MessageType_StoredPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trunk.
        /// </summary>
        internal static string MessageType_Trunk {
            get {
                return ResourceManager.GetString("MessageType_Trunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string MessageType_Yes {
            get {
                return ResourceManager.GetString("MessageType_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extreme Acceleration.
        /// </summary>
        internal static string Violation_Acc_Extreme {
            get {
                return ResourceManager.GetString("Violation_Acc_Extreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harsh Acceleration.
        /// </summary>
        internal static string Violation_Acc_Harsh {
            get {
                return ResourceManager.GetString("Violation_Acc_Harsh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extreme Braking.
        /// </summary>
        internal static string Violation_Braking_Extreme {
            get {
                return ResourceManager.GetString("Violation_Braking_Extreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harsh Braking.
        /// </summary>
        internal static string Violation_Braking_Harsh {
            get {
                return ResourceManager.GetString("Violation_Braking_Harsh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DURATION.
        /// </summary>
        internal static string Violation_DURATION {
            get {
                return ResourceManager.GetString("Violation_DURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seat Belt Violation.
        /// </summary>
        internal static string Violation_Seat_Belt {
            get {
                return ResourceManager.GetString("Violation_Seat_Belt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string Violation_Speed {
            get {
                return ResourceManager.GetString("Violation_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed Violation.
        /// </summary>
        internal static string Violation_Speed_Violation {
            get {
                return ResourceManager.GetString("Violation_Speed_Violation", resourceCulture);
            }
        }
    }
}
