//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SentinelMobile.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HOSResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HOSResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SentinelMobile.Resources.HOSResources", typeof(HOSResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Duty.
        /// </summary>
        public static string AddDuty {
            get {
                return ResourceManager.GetString("AddDuty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Duty successfully. Do you want to add more?.
        /// </summary>
        public static string AddedDutySuccessfully {
            get {
                return ResourceManager.GetString("AddedDutySuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Manual Entry.
        /// </summary>
        public static string AddmanualLog {
            get {
                return ResourceManager.GetString("AddmanualLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Info.
        /// </summary>
        public static string AddTripInfo {
            get {
                return ResourceManager.GetString("AddTripInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adverse Driving Condition.
        /// </summary>
        public static string AdverseDrivingCondition {
            get {
                return ResourceManager.GetString("AdverseDrivingCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Successfully..
        /// </summary>
        public static string ApprovedSuccessfully {
            get {
                return ResourceManager.GetString("ApprovedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to approve the manual entries for .
        /// </summary>
        public static string ApprovePopup {
            get {
                return ResourceManager.GetString("ApprovePopup", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string ApprovePendings
        {
            get
            {
                return ResourceManager.GetString("ApprovePendings", resourceCulture);
            }
        }
        public static string NoPendingListFound
        {
            get
            {
                return ResourceManager.GetString("NoPendingListFound", resourceCulture);
            }
        }
        public static string ApproveWarning
        {
            get
            {
                return ResourceManager.GetString("ApproveWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit without submitting?.
        /// </summary>
        public static string BackConfirm {
            get {
                return ResourceManager.GetString("BackConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the record?.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date is greater than current date..
        /// </summary>
        public static string DateTimeGreateThanCurrent {
            get {
                return ResourceManager.GetString("DateTimeGreateThanCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day1.
        /// </summary>
        public static string Day1 {
            get {
                return ResourceManager.GetString("Day1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day2.
        /// </summary>
        public static string Day2 {
            get {
                return ResourceManager.GetString("Day2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deferrd Hours Under.
        /// </summary>
        public static string DeferredHoursUnder {
            get {
                return ResourceManager.GetString("DeferredHoursUnder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Successfully.
        /// </summary>
        public static string DeleteDutySuccessfully {
            get {
                return ResourceManager.GetString("DeleteDutySuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver.
        /// </summary>
        public static string Driver {
            get {
                return ResourceManager.GetString("Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving.
        /// </summary>
        public static string Driving {
            get {
                return ResourceManager.GetString("Driving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load data, please try again later..
        /// </summary>
        public static string FailedToLoad {
            get {
                return ResourceManager.GetString("FailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save data..
        /// </summary>
        public static string FailedToSave {
            get {
                return ResourceManager.GetString("FailedToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Co-Driver.
        /// </summary>
        public static string InputCoDriver {
            get {
                return ResourceManager.GetString("InputCoDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Company.
        /// </summary>
        public static string InputCompany {
            get {
                return ResourceManager.GetString("InputCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Date.
        /// </summary>
        public static string InputDate {
            get {
                return ResourceManager.GetString("InputDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Deferred Hrs.
        /// </summary>
        public static string InputDeferred {
            get {
                return ResourceManager.GetString("InputDeferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Duty.
        /// </summary>
        public static string InputDuty {
            get {
                return ResourceManager.GetString("InputDuty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Emergency Driving Reason.
        /// </summary>
        public static string InputEmergency {
            get {
                return ResourceManager.GetString("InputEmergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input End Odometer.
        /// </summary>
        public static string InputEndOdometer {
            get {
                return ResourceManager.GetString("InputEndOdometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Equipment No.
        /// </summary>
        public static string InputEquipmentNo {
            get {
                return ResourceManager.GetString("InputEquipmentNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Home Terminal.
        /// </summary>
        public static string InputHomeTerminal {
            get {
                return ResourceManager.GetString("InputHomeTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Personal Use End Odometer.
        /// </summary>
        public static string InputPersonalUseEndOdo {
            get {
                return ResourceManager.GetString("InputPersonalUseEndOdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Personal Use Start Odometer.
        /// </summary>
        public static string InputPersonalUseStartOdo {
            get {
                return ResourceManager.GetString("InputPersonalUseStartOdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Remark.
        /// </summary>
        public static string InputRemark {
            get {
                return ResourceManager.GetString("InputRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Shift Start.
        /// </summary>
        public static string InputShiftStart {
            get {
                return ResourceManager.GetString("InputShiftStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Shipping Document.
        /// </summary>
        public static string InputShippingDocument {
            get {
                return ResourceManager.GetString("InputShippingDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Start Odometer.
        /// </summary>
        public static string InputStartOdometer {
            get {
                return ResourceManager.GetString("InputStartOdometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Time.
        /// </summary>
        public static string InputTime {
            get {
                return ResourceManager.GetString("InputTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Trailer Plate/Unit.
        /// </summary>
        public static string InputTrailerNo {
            get {
                return ResourceManager.GetString("InputTrailerNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Truck/Tractor Plate/Unit.
        /// </summary>
        public static string InputTruckNo {
            get {
                return ResourceManager.GetString("InputTruckNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Last record is neither off duty nor sleeping..
        /// </summary>
        public static string LastRecordNotOffDufty {
            get {
                return ResourceManager.GetString("LastRecordNotOffDufty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logsheets &amp; Inspections.
        /// </summary>
        public static string Logsheets {
            get {
                return ResourceManager.GetString("Logsheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please don&apos;t forget to input your off duty time..
        /// </summary>
        public static string MakeSureLastOffDuty {
            get {
                return ResourceManager.GetString("MakeSureLastOffDuty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Entry.
        /// </summary>
        public static string ManualLogsheets {
            get {
                return ResourceManager.GetString("ManualLogsheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data Found.
        /// </summary>
        public static string NoDataFound {
            get {
                return ResourceManager.GetString("NoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Driver Found.
        /// </summary>
        public static string NoDriverFound {
            get {
                return ResourceManager.GetString("NoDriverFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odometer.
        /// </summary>
        public static string Odometer {
            get {
                return ResourceManager.GetString("Odometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off Duty.
        /// </summary>
        public static string OffDuty {
            get {
                return ResourceManager.GetString("OffDuty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oil Field Waiting Time.
        /// </summary>
        public static string OilFieldWaiting {
            get {
                return ResourceManager.GetString("OilFieldWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Duty.
        /// </summary>
        public static string OnDuty {
            get {
                return ResourceManager.GetString("OnDuty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please.
        /// </summary>
        public static string Please {
            get {
                return ResourceManager.GetString("Please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        public static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Successfully.
        /// </summary>
        public static string SavedSuccessfully {
            get {
                return ResourceManager.GetString("SavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Driver Name.
        /// </summary>
        public static string SearchDrivers {
            get {
                return ResourceManager.GetString("SearchDrivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Action.
        /// </summary>
        public static string SelectAction {
            get {
                return ResourceManager.GetString("SelectAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select City.
        /// </summary>
        public static string SelectCity {
            get {
                return ResourceManager.GetString("SelectCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Cycle.
        /// </summary>
        public static string SelectCycle {
            get {
                return ResourceManager.GetString("SelectCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Duty.
        /// </summary>
        public static string SelectDuty {
            get {
                return ResourceManager.GetString("SelectDuty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Province/State.
        /// </summary>
        public static string SelectProvince {
            get {
                return ResourceManager.GetString("SelectProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep.
        /// </summary>
        public static string Sleep {
            get {
                return ResourceManager.GetString("Sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string TimeRounded
        {
            get
            {
                return ResourceManager.GetString("TimeRounded", resourceCulture);
            }
        }

    }
}
