//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SentinelMobile.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SentinelMobile.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address resolution in progress.
        /// </summary>
        public static string AddressResolutionInProgress {
            get {
                return ResourceManager.GetString("AddressResolutionInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air/Fuel Ratio x 10.
        /// </summary>
        public static string AirFuelRatiox10 {
            get {
                return ResourceManager.GetString("AirFuelRatiox10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armed.
        /// </summary>
        public static string Armed {
            get {
                return ResourceManager.GetString("Armed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Battery.
        /// </summary>
        public static string BackupBattery {
            get {
                return ResourceManager.GetString("BackupBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Layers.
        /// </summary>
        public static string BaseLayers {
            get {
                return ResourceManager.GetString("BaseLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        public static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box.
        /// </summary>
        public static string Box {
            get {
                return ResourceManager.GetString("Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell.
        /// </summary>
        public static string Cell {
            get {
                return ResourceManager.GetString("Cell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Status Info.
        /// </summary>
        public static string CloseStatusInfo {
            get {
                return ResourceManager.GetString("CloseStatusInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closest %num% vehicles.
        /// </summary>
        public static string Closestnumvehicles {
            get {
                return ResourceManager.GetString("Closestnumvehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command successful..
        /// </summary>
        public static string CommandSuccessful {
            get {
                return ResourceManager.GetString("CommandSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command was sent successfully using.
        /// </summary>
        public static string CommandSuccessfulWith {
            get {
                return ResourceManager.GetString("CommandSuccessfulWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command timeout.
        /// </summary>
        public static string CommandTimeOut {
            get {
                return ResourceManager.GetString("CommandTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        public static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criteria.
        /// </summary>
        public static string Criteria {
            get {
                return ResourceManager.GetString("Criteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M/dd/yyyy.
        /// </summary>
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denominator.
        /// </summary>
        public static string Denominator {
            get {
                return ResourceManager.GetString("Denominator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diesel.
        /// </summary>
        public static string Diesel {
            get {
                return ResourceManager.GetString("Diesel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        public static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        public static string DirectionW {
            get {
                return ResourceManager.GetString("DirectionW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain Name for Driver.
        /// </summary>
        public static string Domainname {
            get {
                return ResourceManager.GetString("Domainname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Domain name field is required.
        /// </summary>
        public static string DomainNameRequired {
            get {
                return ResourceManager.GetString("DomainNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver.
        /// </summary>
        public static string Driver {
            get {
                return ResourceManager.GetString("Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Body should not be empty.
        /// </summary>
        public static string EmailBodyNotEmpty {
            get {
                return ResourceManager.GetString("EmailBodyNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Subject should not be empty.
        /// </summary>
        public static string EmailSubjectNotEmpty {
            get {
                return ResourceManager.GetString("EmailSubjectNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email To should not be empty.
        /// </summary>
        public static string EmailToNotEmpty {
            get {
                return ResourceManager.GetString("EmailToNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine Displacement (ml).
        /// </summary>
        public static string EngineDisplacement {
            get {
                return ResourceManager.GetString("EngineDisplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Hierarchy Name.
        /// </summary>
        public static string EnterHierarchyName {
            get {
                return ResourceManager.GetString("EnterHierarchyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Save.
        /// </summary>
        public static string FailedToSave {
            get {
                return ResourceManager.GetString("FailedToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send the email, please try again later..
        /// </summary>
        public static string FailedToSendEmail {
            get {
                return ResourceManager.GetString("FailedToSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set odometer.
        /// </summary>
        public static string FailedToSetOdometer {
            get {
                return ResourceManager.GetString("FailedToSetOdometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to swap the vehicle..
        /// </summary>
        public static string FailedToSwapVehicle {
            get {
                return ResourceManager.GetString("FailedToSwapVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware version.
        /// </summary>
        public static string FirmwareVersion {
            get {
                return ResourceManager.GetString("FirmwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fleets.
        /// </summary>
        public static string Fleets {
            get {
                return ResourceManager.GetString("Fleets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fleet View.
        /// </summary>
        public static string FleetView {
            get {
                return ResourceManager.GetString("FleetView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow.
        /// </summary>
        public static string Follow {
            get {
                return ResourceManager.GetString("Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel.
        /// </summary>
        public static string Fuel {
            get {
                return ResourceManager.GetString("Fuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Type.
        /// </summary>
        public static string FuelType {
            get {
                return ResourceManager.GetString("FuelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get.
        /// </summary>
        public static string Get {
            get {
                return ResourceManager.GetString("Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Box Status.
        /// </summary>
        public static string GetBoxStatus {
            get {
                return ResourceManager.GetString("GetBoxStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Hybrid.
        /// </summary>
        public static string GoogleHybrid {
            get {
                return ResourceManager.GetString("GoogleHybrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Satellite.
        /// </summary>
        public static string GoogleSatellite {
            get {
                return ResourceManager.GetString("GoogleSatellite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Streets.
        /// </summary>
        public static string GoogleStreets {
            get {
                return ResourceManager.GetString("GoogleStreets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS: Invalid.
        /// </summary>
        public static string GpsInvalid {
            get {
                return ResourceManager.GetString("GpsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS: Valid.
        /// </summary>
        public static string GpsValid {
            get {
                return ResourceManager.GetString("GpsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hierarchy.
        /// </summary>
        public static string Hierarchy {
            get {
                return ResourceManager.GetString("Hierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You would remove all history records from your page and map..
        /// </summary>
        public static string HistoryClearMsg {
            get {
                return ResourceManager.GetString("HistoryClearMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installer.
        /// </summary>
        public static string Installer {
            get {
                return ResourceManager.GetString("Installer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installer should not be empty.
        /// </summary>
        public static string InstallerNotEmpty {
            get {
                return ResourceManager.GetString("InstallerNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email Address.
        /// </summary>
        public static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only numbers from 0 to 16777215 allowed.
        /// </summary>
        public static string InvalidOdometer2 {
            get {
                return ResourceManager.GetString("InvalidOdometer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landmark/Geozone.
        /// </summary>
        public static string LandmarkGeozone {
            get {
                return ResourceManager.GetString("LandmarkGeozone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layers.
        /// </summary>
        public static string Layers {
            get {
                return ResourceManager.GetString("Layers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Plate.
        /// </summary>
        public static string LicensePlate {
            get {
                return ResourceManager.GetString("LicensePlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Battery.
        /// </summary>
        public static string MainBattery {
            get {
                return ResourceManager.GetString("MainBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make.
        /// </summary>
        public static string Make {
            get {
                return ResourceManager.GetString("Make", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MDT messages in memory.
        /// </summary>
        public static string MDTmessagesinmemory {
            get {
                return ResourceManager.GetString("MDTmessagesinmemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Usage.
        /// </summary>
        public static string MemoryUsage {
            get {
                return ResourceManager.GetString("MemoryUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mid.
        /// </summary>
        public static string Mid {
            get {
                return ResourceManager.GetString("Mid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Box is not accessible at the moment.
        /// </summary>
        public static string MsgGetCommanStatusFailed {
            get {
                return ResourceManager.GetString("MsgGetCommanStatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural Gas.
        /// </summary>
        public static string NaturalGas {
            get {
                return ResourceManager.GetString("NaturalGas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Box ID (box installed in).
        /// </summary>
        public static string NewBoxId {
            get {
                return ResourceManager.GetString("NewBoxId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non GPS Data.
        /// </summary>
        public static string NonGPSData {
            get {
                return ResourceManager.GetString("NonGPSData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No vehicles.
        /// </summary>
        public static string Novehicles {
            get {
                return ResourceManager.GetString("Novehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NW.
        /// </summary>
        public static string NW {
            get {
                return ResourceManager.GetString("NW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odometer.
        /// </summary>
        public static string Odometer {
            get {
                return ResourceManager.GetString("Odometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Box ID (box taken out).
        /// </summary>
        public static string OldBoxId {
            get {
                return ResourceManager.GetString("OldBoxId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay Layers.
        /// </summary>
        public static string OverlayLayers {
            get {
                return ResourceManager.GetString("OverlayLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Password field is required..
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait....
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium.
        /// </summary>
        public static string Premium {
            get {
                return ResourceManager.GetString("Premium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRL.
        /// </summary>
        public static string PRL {
            get {
                return ResourceManager.GetString("PRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reefer Change Operating Mode.
        /// </summary>
        public static string ReeferChangeOperatingMode {
            get {
                return ResourceManager.GetString("ReeferChangeOperatingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reefer Change Set Point.
        /// </summary>
        public static string ReeferChangeSetPoint {
            get {
                return ResourceManager.GetString("ReeferChangeSetPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reefer Clear Alarm.
        /// </summary>
        public static string ReeferClearAlarm {
            get {
                return ResourceManager.GetString("ReeferClearAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reefer Close Fresh Air Door.
        /// </summary>
        public static string ReeferCloseFreshAirDoor {
            get {
                return ResourceManager.GetString("ReeferCloseFreshAirDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuous Run Mode.
        /// </summary>
        public static string ReeferContinuousRunMode {
            get {
                return ResourceManager.GetString("ReeferContinuousRunMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle Sentry Mode.
        /// </summary>
        public static string ReeferCycleSentryMode {
            get {
                return ResourceManager.GetString("ReeferCycleSentryMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reefer Initiate De-frost.
        /// </summary>
        public static string ReeferInitiateDefrost {
            get {
                return ResourceManager.GetString("ReeferInitiateDefrost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reefer Initiate Pre-Trip.
        /// </summary>
        public static string ReeferInitiatePreTrip {
            get {
                return ResourceManager.GetString("ReeferInitiatePreTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reefer Multiple Alarm Read.
        /// </summary>
        public static string ReeferMultipleAlarmRead {
            get {
                return ResourceManager.GetString("ReeferMultipleAlarmRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reefer Open Fresh Air Door.
        /// </summary>
        public static string ReeferOpenFreshAirDoor {
            get {
                return ResourceManager.GetString("ReeferOpenFreshAirDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep Mode.
        /// </summary>
        public static string ReeferSleepMode {
            get {
                return ResourceManager.GetString("ReeferSleepMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reefer Software Identification.
        /// </summary>
        public static string ReeferSoftwareIdentification {
            get {
                return ResourceManager.GetString("ReeferSoftwareIdentification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reefer Turn Power Off.
        /// </summary>
        public static string ReeferTurnPowerOff {
            get {
                return ResourceManager.GetString("ReeferTurnPowerOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reefer Turn Power On.
        /// </summary>
        public static string ReeferTurnPowerOn {
            get {
                return ResourceManager.GetString("ReeferTurnPowerOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular.
        /// </summary>
        public static string Regular {
            get {
                return ResourceManager.GetString("Regular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPM.
        /// </summary>
        public static string RPM {
            get {
                return ResourceManager.GetString("RPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveSensorList {
            get {
                return ResourceManager.GetString("SaveSensorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Criteria.
        /// </summary>
        public static string SearchCriteria {
            get {
                return ResourceManager.GetString("SearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Fleets.
        /// </summary>
        public static string SearchFleets {
            get {
                return ResourceManager.GetString("SearchFleets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Street info to search closest vehicles.
        /// </summary>
        public static string SearchForClosestVehicles {
            get {
                return ResourceManager.GetString("SearchForClosestVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Radius.
        /// </summary>
        public static string SearchRadius {
            get {
                return ResourceManager.GetString("SearchRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Vehicle Name.
        /// </summary>
        public static string SearchVehicles {
            get {
                return ResourceManager.GetString("SearchVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send command failed using.
        /// </summary>
        public static string SendCommandFailedUsing {
            get {
                return ResourceManager.GetString("SendCommandFailedUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Email.
        /// </summary>
        public static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending Second ECM Seatbelt Odometer ....
        /// </summary>
        public static string SendingSecondECMSeatbeltOdometer {
            get {
                return ResourceManager.GetString("SendingSecondECMSeatbeltOdometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending Third ECM Seatbelt Odometer ....
        /// </summary>
        public static string SendingThirdECMSeatbeltOdometer {
            get {
                return ResourceManager.GetString("SendingThirdECMSeatbeltOdometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor List.
        /// </summary>
        public static string SensorList {
            get {
                return ResourceManager.GetString("SensorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensors.
        /// </summary>
        public static string Sensors {
            get {
                return ResourceManager.GetString("Sensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Status.
        /// </summary>
        public static string SensorStatus {
            get {
                return ResourceManager.GetString("SensorStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session time out.
        /// </summary>
        public static string SessionTimeOut {
            get {
                return ResourceManager.GetString("SessionTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        public static string Set {
            get {
                return ResourceManager.GetString("Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetFuelConfiguration.
        /// </summary>
        public static string SetFuelConfiguration {
            get {
                return ResourceManager.GetString("SetFuelConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECM Seatbelt Odometer.
        /// </summary>
        public static string SetSeatbeltOdometer {
            get {
                return ResourceManager.GetString("SetSeatbeltOdometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM/ESN.
        /// </summary>
        public static string SIMESN {
            get {
                return ResourceManager.GetString("SIMESN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.N.
        /// </summary>
        public static string SN {
            get {
                return ResourceManager.GetString("SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Km/h.
        /// </summary>
        public static string SpeedKm {
            get {
                return ResourceManager.GetString("SpeedKm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mph.
        /// </summary>
        public static string SpeedMile {
            get {
                return ResourceManager.GetString("SpeedMile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State/Province.
        /// </summary>
        public static string StateProvince {
            get {
                return ResourceManager.GetString("StateProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Saved!.
        /// </summary>
        public static string SuccessfullySaved {
            get {
                return ResourceManager.GetString("SuccessfullySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email was send successfully..
        /// </summary>
        public static string SuccessfullySendEmail {
            get {
                return ResourceManager.GetString("SuccessfullySendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully swapped the vehicle..
        /// </summary>
        public static string SuccessfullySwapVehicle {
            get {
                return ResourceManager.GetString("SuccessfullySwapVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SW.
        /// </summary>
        public static string SW {
            get {
                return ResourceManager.GetString("SW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap.
        /// </summary>
        public static string Swap {
            get {
                return ResourceManager.GetString("Swap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to swap?.
        /// </summary>
        public static string SwapConfirmMsg {
            get {
                return ResourceManager.GetString("SwapConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hh:mm tt.
        /// </summary>
        public static string TimeFormat {
            get {
                return ResourceManager.GetString("TimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfollow.
        /// </summary>
        public static string Unfollow {
            get {
                return ResourceManager.GetString("Unfollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unused.
        /// </summary>
        public static string Unused {
            get {
                return ResourceManager.GetString("Unused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Position.
        /// </summary>
        public static string UpdatePosition {
            get {
                return ResourceManager.GetString("UpdatePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update vehicle name failed..
        /// </summary>
        public static string UpdateVehicleNameFail {
            get {
                return ResourceManager.GetString("UpdateVehicleNameFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated vehicle name..
        /// </summary>
        public static string UpdateVehicleNameSuccess {
            get {
                return ResourceManager.GetString("UpdateVehicleNameSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password provided is incorrect..
        /// </summary>
        public static string UserNamePasswordIncorrect {
            get {
                return ResourceManager.GetString("UserNamePasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The User name field is required..
        /// </summary>
        public static string UserNameRequired {
            get {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Name.
        /// </summary>
        public static string VehicleName {
            get {
                return ResourceManager.GetString("VehicleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicles.
        /// </summary>
        public static string Vehicles {
            get {
                return ResourceManager.GetString("Vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensors.
        /// </summary>
        public static string VehicleSensors {
            get {
                return ResourceManager.GetString("VehicleSensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Type.
        /// </summary>
        public static string VehicleType {
            get {
                return ResourceManager.GetString("VehicleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View full size.
        /// </summary>
        public static string ViewFullSize {
            get {
                return ResourceManager.GetString("ViewFullSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIN.
        /// </summary>
        public static string VIN {
            get {
                return ResourceManager.GetString("VIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIN should always be 17 characters..
        /// </summary>
        public static string VIN17Characters {
            get {
                return ResourceManager.GetString("VIN17Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volt.
        /// </summary>
        public static string Volt {
            get {
                return ResourceManager.GetString("Volt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Efficency (0-100%).
        /// </summary>
        public static string VolumeEfficency {
            get {
                return ResourceManager.GetString("VolumeEfficency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to West.
        /// </summary>
        public static string West {
            get {
                return ResourceManager.GetString("West", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
